yiisoft/form-model

composer.json
config/di.php
tests/ConfigTest.php

Add config

---

.github/workflows/build.yml
.github/workflows/mutation.yml
tests/Field/ErrorSummaryTest.php
tests/Support/Form/DateForm.php
tests/Support/Form/EmailForm.php
tests/Support/Form/ErrorSummaryForm.php
tests/Support/Form/FileForm.php
tests/Support/Form/NumberForm.php
tests/Support/Form/PasswordForm.php
tests/Support/Form/RangeForm.php
tests/Support/Form/SelectForm.php
tests/Support/Form/TelephoneForm.php
tests/Support/Form/TextForm.php
tests/Support/Form/TextareaForm.php
tests/Support/Form/UrlForm.php
tests/Support/StubDateTimeInputField.php
tests/ValidationRulesEnricherTest.php

Add more tests

---

src/FormHydrator.php
src/Safe.php
tests/FormModelTest.php
tests/Support/Form/FormWithNestedStructures.php
tests/Support/Form/LoginForm.php
tests/Support/Form/NestedRuleForm/MainForm.php

By default, fill form model properties with rules only

---

src/Field.php
tests/FieldTest.php

Add `url` parameter to `Field::image()`

---

src/FieldFactory.php
tests/FieldFactoryTest.php

Add `FieldFactory`

---

src/FormHydrator.php
tests/FormHydratorTest.php
tests/Support/Form/CarForm.php
tests/Support/TestHelper.php

Add `FormHydrator::populateAndValidate()`

---

.github/workflows/build.yml
README.md
composer.json
phpunit.xml.dist
psalm.xml
src/FormHydrator.php
src/FormModel.php
src/FormModelInputData.php
tests/FieldTest.php
tests/FormModelInputDataTest.php
tests/FormModelTest.php
tests/SafeTest.php
tests/Support/StubField.php
tests/ValidationRulesEnricherTest.php

Test coverage 100%, Psalm 1, Kill several mutants

---

composer.json
src/FormHydrator.php
tests/FormHydratorTest.php

Add `FormHydrator::populateFromPost()` and `FormHydrator::populateFromPostAndValidate()`

---

composer.json

Use stable version of `yiisoft/hydrator-validator`

---

src/ValidationRulesEnricher.php

Improve `ValidationRulesEnricher`

---

config/di.php
src/NonArrayTypeCaster.php
tests/NonArrayTypeCasterTest.php
tests/Support/TestHelper.php

Add `NonArrayTypeCaster`

---

composer.json
src/Field.php
src/FieldFactory.php
src/FormModel.php
src/FormModelInputData.php
src/FormModelInterface.php

Raise `yiisoft/hydrator-validator` to `^2.0`

---

README.md
composer.json
src/Exception/PropertyNotSupportNestedValuesException.php
src/Exception/StaticObjectPropertyException.php
src/Exception/UndefinedArrayElementException.php
src/Exception/UndefinedObjectPropertyException.php
src/Exception/ValueNotFoundException.php
src/Field.php
src/FieldFactory.php
src/FormHydrator.php
src/FormModel.php
src/FormModelInterface.php
src/NonArrayTypeCaster.php
src/Safe.php
src/ValidationRulesEnricher.php
tests/FieldFactoryTest.php
tests/FieldTest.php
tests/FormHydratorTest.php
tests/FormModelTest.php
tests/ValidationRulesEnricherTest.php

Cleanup and docs

---

tests/ValidationRulesEnricherTest.php

Sync with form changes

---

composer.json
src/Field.php
src/FormModel.php

Fix psalm errors

---

src/FormModel.php
src/FormModelInterface.php
tests/FormModelTest.php

Add `FormModel::addError()`

---

composer.json
src/Field.php
src/FieldFactory.php
src/FormModelInputData.php
tests/FieldFactoryTest.php
tests/FieldTest.php
tests/FormModelTest.php

Adapt to Yii Validator 2

---

composer.json

Update hydrator version

---

src/ValidationRulesEnricher.php

Refactor validation rules enricher

---

docs/guide/en/form-hydrator.md

Docs, hydrator extensions

---

README.md
src/FormModel.php
tests/FormModelTest.php
tests/Support/Form/LabelForm.php

Add `Label` attribute support

---

CHANGELOG.md
composer.json
src/FormHydrator.php
tests/FormHydratorTest.php

| Is bugfix?    | ✔️/❌
| Breaks BC?    | ✔️/❌

Merge properties from `getRules()` and from PHP attrs

---

.github/workflows/rector.yml

Fix rector CI

---

.github/workflows/bc.yml

Enable BC checker
